### ISSUE TITLE
Submit a Poll Response

### ISSUE THREAD

**Issue by matt-rodrigues** [matt-rodrigues/Love-Running-Agile#1]
**Feature: Submit. a Poll Response**

**User Story 1:**
_In order to_ provide my opnion with regards to a certain running topica or event as a user, _I can_ select and submit an answer from the poll.

**User Story 2:** _In order to_ provide anonymous feedback as a user, _I can_ choose to hide my identity in the poll response.

**User Story 3:** _In order to_ provide additional thoughts beyond the response options as a user, _I can_ add comment before I submit my poll response.

**Comment by matt-rodrigues** [comment]
In order to **receive benefiti** as a **role**, I can **goal/desire**

**Acceptance Criteria**

- Acceptance Criteria 1:
- Acceptance Criteria 2:
- Acceptance Criteria 3:

**Comment by matt-rodrigues** [comment]
**User Story:** In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response

**Acceptance Criteria:**
> **a.** The poll should disappear at 11:59 PM on the target date
>**b.** The real estate of the "Poll" should be reserved on the home page. a message that says "Stay Tuned, a new poll is comimg soon" should appear if no other Poll is active.
>**c.** The administrator expiry date should be at least 3 days after the current date.

##Task:
- [ ]  Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: shoe "Stay tuned, a new poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
